package com.child.entity;

import org.greenrobot.greendao.annotation.*;

import java.io.Serializable;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.
/**
 * Entity mapped to table "CHILD".
 */
@Entity
public class Child implements Serializable{

    @Id
    private Long id;
    private String name;
    private Integer sex;
    private Integer age;
    private String birthday;
    private Integer head_pic;
    private String game_app;
    private String book_app;
    private String animation_app;
    private String learn_app;

    @Generated
    public Child() {
    }

    public Child(Long id) {
        this.id = id;
    }

    @Generated
    public Child(Long id, String name, Integer sex, Integer age, String birthday, Integer head_pic, String game_app, String book_app, String animation_app, String learn_app) {
        this.id = id;
        this.name = name;
        this.sex = sex;
        this.age = age;
        this.birthday = birthday;
        this.head_pic = head_pic;
        this.game_app = game_app;
        this.book_app = book_app;
        this.animation_app = animation_app;
        this.learn_app = learn_app;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public Integer getAge() {
        return age;
    }

    public void setAge(Integer age) {
        this.age = age;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public Integer getHead_pic() {
        return head_pic;
    }

    public void setHead_pic(Integer head_pic) {
        this.head_pic = head_pic;
    }

    public String getGame_app() {
        return game_app;
    }

    public void setGame_app(String game_app) {
        this.game_app = game_app;
    }

    public String getBook_app() {
        return book_app;
    }

    public void setBook_app(String book_app) {
        this.book_app = book_app;
    }

    public String getAnimation_app() {
        return animation_app;
    }

    public void setAnimation_app(String animation_app) {
        this.animation_app = animation_app;
    }

    public String getLearn_app() {
        return learn_app;
    }

    public void setLearn_app(String learn_app) {
        this.learn_app = learn_app;
    }

}
